### ISSUE TITLE
Can't install plugin

### ISSUE THREAD

**Issue by Chris2011** [ericsonj/atmel-plugin#2]
I downloaded your plugin from the plugin page and when I want to install it, I choose the file and hit ok and nothing happened. No info in the IDE log and not exception. The Download section is empty and will not take the atmel-plugin.

**Comment by ericsonj** [comment]
Hi Chris2011

This plugin only work in GNU/Linux, but I have been working in the fork and branch atmel-project, You could try with this. 

https://github.com/ericsonj/arduino-netbeans

**Comment by Chris2011** [comment]
Thx I will have a look :)

**Comment by Chris2011** [comment]
Can install it via plugin-center. Thx. :)
